services:
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    env_file: ./.secrets/app-dev.env

  db:
    image: postgres:16
    ports:
      - "5432:5432" # Expose port for accessing the database
    volumes:
      - postgres_data:/var/lib/postgresql/data # Create a volume for storing database data
    env_file: ./.secrets/db-dev.env

volumes:
  postgres_data:
